// ======================================================
// MINING TYCOON 3D
// GLOBAL GAME STATE
// ======================================================
//
// ECONOMY:
//
// ETH
//   -> Used to purchase mining hardware.
//
// TYCON
//   -> Token reward generated by active miners.
//
// Power
//   -> Determines whether mining hardware can operate.
//
// ======================================================

export type GameStateListener = (
  state: GameState
) => void;

export default class GameState {
  // ====================================================
  // TYCON ECONOMY
  // ====================================================
  //
  // New players start with ZERO TYCON.
  //
  // Their starter hardware will be granted separately
  // through the starter pack system.
  // ====================================================

  private tyconBalance =
    0;

  // ====================================================
  // MINING STATE
  // ====================================================

  // Total ACTIVE mining hashrate in MH/s.
  private totalHashrate =
    0;

  // Total ACTIVE power consumption in watts.
  private totalPowerUsage =
    0;

  // ====================================================
  // MINING ECONOMY SETTINGS
  // ====================================================
  //
  // TYCON generated by 1 MH/s every second.
  //
  // IMPORTANT:
  // This is only the game economy rate.
  //
  // We can rebalance this later when we know:
  //
  // - TYCON total supply
  // - token allocation
  // - mining allocation
  // - expected players
  // - expected hardware progression
  // - mining emission period
  //
  // ====================================================

  private readonly tyconPerMHPerSecond =
    0.00015;

  // ====================================================
  // STATISTICS
  // ====================================================

  // Total TYCON mined during this player's lifetime.
  private totalTyconMined =
    0;

  // ====================================================
  // EVENT LISTENERS
  // ====================================================

  private listeners:
    GameStateListener[] = [];

  // ====================================================
  // UPDATE
  // ====================================================
  //
  // Called every game frame.
  //
  // Active hashrate generates TYCON continuously.
  // ====================================================

  public update(
    delta: number
  ) {
    if (
      delta <= 0 ||
      this.totalHashrate <= 0
    ) {
      return;
    }

    // ----------------------------------------------
    // TYCON MINING
    // ----------------------------------------------

    const minedTycon =
      this.totalHashrate *
      this.tyconPerMHPerSecond *
      delta;

    if (
      minedTycon <= 0
    ) {
      return;
    }

    // ----------------------------------------------
    // ADD MINING REWARD
    // ----------------------------------------------

    this.tyconBalance +=
      minedTycon;

    this.totalTyconMined +=
      minedTycon;

    this.notifyListeners();
  }

  // ====================================================
  // ADD TYCON
  // ====================================================
  //
  // Useful later for:
  //
  // - quests
  // - events
  // - achievements
  // - admin rewards
  // - migrations
  //
  // This should NOT eventually be trusted directly
  // for withdrawals. The backend will become the
  // authoritative TYCON ledger.
  // ====================================================

  public addTycon(
    amount: number
  ) {
    if (
      !Number.isFinite(amount) ||
      amount <= 0
    ) {
      return;
    }

    this.tyconBalance +=
      amount;

    this.notifyListeners();
  }

  // ====================================================
  // REMOVE TYCON
  // ====================================================
  //
  // Useful later if TYCON gets in-game utility.
  //
  // Example:
  // upgrades / crafting / boosts.
  // ====================================================

  public spendTycon(
    amount: number
  ): boolean {
    if (
      !Number.isFinite(amount) ||
      amount <= 0
    ) {
      return false;
    }

    if (
      this.tyconBalance <
      amount
    ) {
      return false;
    }

    this.tyconBalance -=
      amount;

    this.notifyListeners();

    return true;
  }

  // ====================================================
  // CAN AFFORD TYCON COST
  // ====================================================

  public canAffordTycon(
    amount: number
  ): boolean {
    if (
      !Number.isFinite(amount) ||
      amount < 0
    ) {
      return false;
    }

    return (
      this.tyconBalance >=
      amount
    );
  }

  // ====================================================
  // SET TYCON BALANCE
  // ====================================================
  //
  // Needed later when loading the player's save
  // from the backend/database.
  // ====================================================

  public setTyconBalance(
    amount: number
  ) {
    if (
      !Number.isFinite(amount)
    ) {
      return;
    }

    this.tyconBalance =
      Math.max(
        0,
        amount
      );

    this.notifyListeners();
  }

  // ====================================================
  // MINING HARDWARE
  // ====================================================

  public addMiningPower(
    hashRate: number,
    powerUsage: number
  ) {
    const safeHashrate =
      Number.isFinite(hashRate)
        ? Math.max(
            0,
            hashRate
          )
        : 0;

    const safePowerUsage =
      Number.isFinite(powerUsage)
        ? Math.max(
            0,
            powerUsage
          )
        : 0;

    this.totalHashrate +=
      safeHashrate;

    this.totalPowerUsage +=
      safePowerUsage;

    this.notifyListeners();
  }

  // ====================================================
  // REMOVE MINING HARDWARE
  // ====================================================

  public removeMiningPower(
    hashRate: number,
    powerUsage: number
  ) {
    const safeHashrate =
      Number.isFinite(hashRate)
        ? Math.max(
            0,
            hashRate
          )
        : 0;

    const safePowerUsage =
      Number.isFinite(powerUsage)
        ? Math.max(
            0,
            powerUsage
          )
        : 0;

    this.totalHashrate =
      Math.max(
        0,
        this.totalHashrate -
          safeHashrate
      );

    this.totalPowerUsage =
      Math.max(
        0,
        this.totalPowerUsage -
          safePowerUsage
      );

    this.notifyListeners();
  }

  // ====================================================
  // MINING RATE
  // ====================================================

  public getTyconPerSecond():
    number {
    return (
      this.totalHashrate *
      this.tyconPerMHPerSecond
    );
  }

  // ====================================================
  // ESTIMATED TYCON PER MINUTE
  // ====================================================

  public getTyconPerMinute():
    number {
    return (
      this.getTyconPerSecond() *
      60
    );
  }

  // ====================================================
  // ESTIMATED TYCON PER HOUR
  // ====================================================

  public getTyconPerHour():
    number {
    return (
      this.getTyconPerSecond() *
      3600
    );
  }

  // ====================================================
  // TYCON BALANCE
  // ====================================================

  public getTyconBalance():
    number {
    return this.tyconBalance;
  }

  // ====================================================
  // HASHRATE
  // ====================================================

  public getHashrate():
    number {
    return this.totalHashrate;
  }

  // ====================================================
  // POWER USAGE
  // ====================================================

  public getPowerUsage():
    number {
    return this.totalPowerUsage;
  }

  // ====================================================
  // TOTAL TYCON MINED
  // ====================================================

  public getTotalTyconMined():
    number {
    return this.totalTyconMined;
  }

  // ====================================================
  // SET TOTAL TYCON MINED
  // ====================================================
  //
  // Used later when restoring statistics from save.
  // ====================================================

  public setTotalTyconMined(
    amount: number
  ) {
    if (
      !Number.isFinite(amount)
    ) {
      return;
    }

    this.totalTyconMined =
      Math.max(
        0,
        amount
      );

    this.notifyListeners();
  }

  // ====================================================
  // EVENTS
  // ====================================================

  public subscribe(
    listener: GameStateListener
  ) {
    this.listeners.push(
      listener
    );

    // Immediately send current state.
    listener(
      this
    );

    return () => {
      this.listeners =
        this.listeners.filter(
          (item) =>
            item !== listener
        );
    };
  }

  // ====================================================
  // NOTIFY
  // ====================================================

  private notifyListeners() {
    for (
      const listener
      of this.listeners
    ) {
      listener(
        this
      );
    }
  }
}
