// ======================================================
// MINING TYCOON 3D
// Mining Hardware Database
// ======================================================

export type MinerTier =
  | "starter"
  | "basic"
  | "advanced"
  | "industrial"
  | "elite";

export type MinerDefinition = {
  // Unique internal ID.
  id: string;

  // Display name.
  name: string;

  // Hardware manufacturer.
  manufacturer: string;

  // Hardware tier.
  tier: MinerTier;

  // Purchase price.
  price: number;

  // Mining performance in MH/s.
  hashRate: number;

  // Electricity consumption in watts.
  powerUsage: number;

  // Heat generated by the machine.
  heatOutput: number;

  // Number of rack slots required.
  rackSlots: number;

  // Short shop description.
  description: string;
};

// ======================================================
// MINER DATABASE
// ======================================================

export const MINERS: MinerDefinition[] = [
  // ----------------------------------------------------
  // STARTER
  // ----------------------------------------------------

  {
    id: "bitforge_s1",

    name: "BitForge S1",

    manufacturer: "BitForge",

    tier: "starter",

    price: 350,

    hashRate: 35,

    powerUsage: 420,

    heatOutput: 18,

    rackSlots: 1,

    description:
      "Cheap entry-level mining server. Low performance, but easy to power.",
  },

  // ----------------------------------------------------
  // BASIC
  // ----------------------------------------------------

  {
    id: "bitforge_s2",

    name: "BitForge S2",

    manufacturer: "BitForge",

    tier: "basic",

    price: 650,

    hashRate: 75,

    powerUsage: 680,

    heatOutput: 27,

    rackSlots: 1,

    description:
      "Improved BitForge miner with better hashrate and efficiency.",
  },

  {
    id: "hashcore_m1",

    name: "HashCore M1",

    manufacturer: "HashCore",

    tier: "basic",

    price: 950,

    hashRate: 125,

    powerUsage: 900,

    heatOutput: 34,

    rackSlots: 1,

    description:
      "Balanced mining server designed for small mining facilities.",
  },

  // ----------------------------------------------------
  // ADVANCED
  // ----------------------------------------------------

  {
    id: "hashcore_m2",

    name: "HashCore M2",

    manufacturer: "HashCore",

    tier: "advanced",

    price: 1750,

    hashRate: 260,

    powerUsage: 1350,

    heatOutput: 48,

    rackSlots: 2,

    description:
      "High-density mining server with serious processing power.",
  },

  {
    id: "nexahash_x1",

    name: "NexaHash X1",

    manufacturer: "NexaHash",

    tier: "advanced",

    price: 2800,

    hashRate: 470,

    powerUsage: 1900,

    heatOutput: 65,

    rackSlots: 2,

    description:
      "Efficient professional miner built for expanding facilities.",
  },

  // ----------------------------------------------------
  // INDUSTRIAL
  // ----------------------------------------------------

  {
    id: "nexahash_x2",

    name: "NexaHash X2",

    manufacturer: "NexaHash",

    tier: "industrial",

    price: 5200,

    hashRate: 950,

    powerUsage: 3100,

    heatOutput: 95,

    rackSlots: 3,

    description:
      "Industrial mining hardware requiring serious power and cooling.",
  },

  {
    id: "quantum_mine_q1",

    name: "QuantumMine Q1",

    manufacturer: "QuantumMine",

    tier: "industrial",

    price: 9500,

    hashRate: 1900,

    powerUsage: 4800,

    heatOutput: 135,

    rackSlots: 3,

    description:
      "High-performance industrial miner for large-scale operations.",
  },

  // ----------------------------------------------------
  // ELITE
  // ----------------------------------------------------

  {
    id: "quantum_mine_qx",

    name: "QuantumMine QX",

    manufacturer: "QuantumMine",

    tier: "elite",

    price: 18500,

    hashRate: 4200,

    powerUsage: 7200,

    heatOutput: 190,

    rackSlots: 4,

    description:
      "Extreme-density mining system designed for data-center scale farms.",
  },
];

// ======================================================
// HELPERS
// ======================================================

export function getMinerById(
  id: string
): MinerDefinition | undefined {
  return MINERS.find(
    (miner) =>
      miner.id === id
  );
}

// ======================================================
// EFFICIENCY
//
// Returns MH/s generated for every watt consumed.
//
// Higher = better.
// ======================================================

export function getMinerEfficiency(
  miner: MinerDefinition
): number {
  if (
    miner.powerUsage <= 0
  ) {
    return 0;
  }

  return (
    miner.hashRate /
    miner.powerUsage
  );
}

// ======================================================
// HASH PER DOLLAR
//
// Useful later for shop comparisons.
// ======================================================

export function getHashPerDollar(
  miner: MinerDefinition
): number {
  if (
    miner.price <= 0
  ) {
    return 0;
  }

  return (
    miner.hashRate /
    miner.price
  );
}

// ======================================================
// TIER DISPLAY NAME
// ======================================================

export function getTierName(
  tier: MinerTier
): string {
  switch (tier) {
    case "starter":
      return "Starter";

    case "basic":
      return "Basic";

    case "advanced":
      return "Advanced";

    case "industrial":
      return "Industrial";

    case "elite":
      return "Elite";

    default:
      return "Unknown";
  }
}
